### PR TITLE
Display normalized EUR/CCD exchange rate

### LINKED ISSUE #94: Better representation of date and conversation rate display for CCD/EUR tool
**Bug Description**
* The CCD/EUR exchange rate update tool triggers immediate effective time of the exchange rate update, which is currently shown as 
`Update enqueued to take effect 1970-01-01 01:00:00.00 UTC+1`. This must be changed to either the correct date or maybe just "immediately".

* The exchange rate is shown as e.g.
`Update the CCD to Euro conversion rate to 1099511627776 EUR = 7923234721.380352 CCD`. This should be changed to a rounded value as `1 EUR = xyz CCD`.

The CCD/EUR tool updates the exchange rate currently every 30 minutes on testnet, see e.g.
* https://dashboard.testnet.concordium.com/chain/6fbc2b29f5878a51834ff02dd9149267591655deb1e9a8e84120fa227c17b9ad
* https://dashboard.testnet.concordium.com/chain/860de7b2b0e0dbd01f5d9212ec4e6e85a3d7504e8444278ff525df9f5ee004ca

**Versions**
- Dashboard v1.0.4

### PR DESCRIPTION
**Pull request by mkmks**
## Purpose

The CCD/EUR exchange rate should be shown as "1 EUR = X CCD" in update event list. 

Closes #94 

## Changes

The exchange rate is received from the CCD2EUR services as a fraction, where the nominator stands for microCCDs, and the denominator stands for euro. To display the exchange rate as "1 EUR = X CCD", one takes the whole part of the nominator divided by the denominator. There's no loss of precision because we assume microCCDs to be the smallest unit of CCD.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [X] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [X] (If necessary) I have updated the CHANGELOG.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

### CODE REVIEW

File: src/elm/Explorer/View.elm [hunk 1]
```diff
@@ -1918,9 +1918,8 @@ viewEventUpdateEnqueuedDetails ctx event =
             row [ width fill ]
                 [ text <|
                     "Update the CCD to Euro conversion rate to "
-                        ++ String.fromInt microCCDPerEuro.denominator
-                        ++ " EUR = "
-                        ++ (T.amountToString <| T.amountFromInt microCCDPerEuro.numerator)
+                        ++ "1 EUR = "
+                        ++ (T.amountToString <| T.amountFromInt (microCCDPerEuro.numerator // microCCDPerEuro.denominator))
```
Comment (abizjak) [inline src/elm/Explorer/View.elm:1922]: Does this also address the weird rounding?

Because in this block https://dashboard.testnet.concordium.com/chain/6fbc2b29f5878a51834ff02dd9149267591655deb1e9a8e84120fa227c17b9ad the actual exchange rate is `1099511627776 / 14353114003361380859` which is not what is displayed on the network dashboard, so I assumed that either the JSON parsing already introduces loss of precision, or `amountFromInt` does.

Comment (abizjak) [reply src/elm/Explorer/View.elm:1922]: Hmm, it looks like it does fix it.
Screenshot from 2022-02-17 09-48-30

I wonder where the rounding came from then.

Comment (abizjak) [reply src/elm/Explorer/View.elm:1922]: It must be amountFromInt that is essentially broken then for large values.

**Review by abizjak — APPROVED** [review]
