### PR TITLE
Ignore old nodes in computing summaries

### LINKED ISSUE #88: Network dashboard computes averages in an unstable way in some cases.
**Description**

Some of the statistics, such as total length and last finalization are computed (at least partly) by taking the value with maximum frequency.
After a protocol update, if the nodes have not upgraded they remain stuck at the height of the protocol update. Since the remaining nodes take a few seconds to update when they receive a new block, or finalize, there are cases where the maximum frequency, e.g., finalized height, is indeed the old one. Hence the flip flopping can sometimes be seen on the network dashboard.

The network dashboard should be configure so that it excludes nodes with too old version from calculation of averages. This should be a build-time parameter.

**Steps to Reproduce**

See description.

**Expected Result**

No flip flopping. Averages are stable.

**Actual Result**

Occasional flip-flopping. Averages fluctuate.

**Versions**
- Software Version: All current versions.

### PR DESCRIPTION
**Pull request by abizjak**
## Purpose

Fixes #88 

## Changes

Ignore old versions in statistics calculations. Introduces a new environment variable `STATS_VERSION`.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: src/elm/Network.elm [hunk 1]
```diff
@@ -250,7 +250,11 @@ viewSummaryWidgets ctx remoteNodes =
                   , icon = Icons.lastBlock iconSize
                   , value =
                         RemoteData.map
-                            (\nodes ->
+                            (\nodesDict ->
+                                let
+                                    compatibleNodes =
+                                        Dict.filter (\_ node -> node.client >= ctx.statsVersion) nodesDict
```
Comment (bisgardo) [inline src/elm/Network.elm:256]: If at some point we have node version 10 then those nodes would be filtered out here.

File: README.md [hunk 2]
```diff
@@ -28,24 +28,28 @@ The development server will proxy some requests to either of these and must be p
 
 To use the development server with a local middleware and collector backend run:
 ```
-CONCORDIUM_MIDDLEWARE_URL='http://localhost:8081' CONCORDIUM_COLLECTOR_BACKEND_URL='http://localhost:12000' npm run dev
+STATS_VERSION=3 CONCORDIUM_MIDDLEWARE_URL='http://localhost:8081' CONCORDIUM_COLLECTOR_BACKEND_URL='http://localhost:12000' npm run dev
```
Comment (bisgardo) [inline README.md:31]: If `STATS_VERSION` defaulted to the empty string then it would not filter out any versions. So I think we could reasonably omit it in these commands.

File: Jenkinsfile [hunk 3]
```diff
@@ -15,7 +16,7 @@ pipeline {
         stage('build') {
             steps {
                 sh '''\
-                  docker build -t "${image_name}" -f k8s.Dockerfile .
+                  docker build --build-arg stats_version=${stats_version} --label stats_version=${stats_version} -t "${image_name}" -f k8s.Dockerfile .
```
Comment (bisgardo) [inline Jenkinsfile:19]: Annoying that it has to be baked into the build, but I see why it can't be a runtime param atm.

File: src/elm/Main.elm [hunk 4]
```diff
@@ -46,6 +46,10 @@ type alias Flags =
     , isProduction : Bool
     , version : Version
     , showCookieConsentBanner : Bool
+
+    -- Minimum version of the node that will be taken
+    -- into account when computing statistics
+    , statsVersion : Version
```
Comment (bisgardo) [inline src/elm/Main.elm:52]: I read `statsVersion` as there being multiple versions of the stats computation method. What about `minVersionIncludedInStats`?

**Review by bisgardo — APPROVED** [review]

File: src/elm/Network.elm (hunk 1 above)
Comment (abizjak) [reply src/elm/Network.elm:256]: Indeed.

I'll add a note to the readme, but I don't want to deal with this now, seeing that it will happen in years.

File: README.md (hunk 2 above)
Comment (abizjak) [reply README.md:31]: I deliberately did not want it to default to anything, since it is then easy to forget if it does.

File: Jenkinsfile (hunk 3 above)
Comment (abizjak) [reply Jenkinsfile:19]: elm ftw

File: src/elm/Main.elm (hunk 4 above)
Comment (abizjak) [reply src/elm/Main.elm:52]: Ok, I'll rename.

File: src/elm/Network.elm (hunk 1 above)
Comment (abizjak) [reply src/elm/Network.elm]: I factored all these checks into a single function, and added a comment to that function.

File: src/elm/Network.elm [hunk 5]
```diff
@@ -355,6 +384,16 @@ nodePeersOnly nodes =
     nodes |> Dict.filter (\_ n -> n.peerType == "Node")
 
 
+
+-- Check whether the client version is recent enough.
+-- NB: This will only work until we have node version 10, after that it needs to be revised.
+
+
+allowedNodeVersion : { ctx | minVersionIncludedInStats : String } -> { a | client : String } -> Bool
```
Comment (Bargsteen) [inline src/elm/Network.elm:392]:
```suggestion
{-| Check whether the client version is recent enough.
NB: This will only work until we have node version 10, after that it needs to be revised.
-}
allowedNodeVersion : { ctx | minVersionIncludedInStats : String } -> { a | client : String } -> Bool
```

**Review by Bargsteen — APPROVED** [review]
Looks good, just a minor fix to a comment :)

File: src/elm/Network.elm (hunk 5 above)
Comment (abizjak) [reply src/elm/Network.elm]: Applied.
